### ISSUE TITLE
DoS Attack: Server crashes when processing new connections ids that have the same cid

### ISSUE THREAD

**Issue by hashkash** [NTAP/quant#68]
Hey Lars,

I've been testing quant and looks like I found a bug that crashes the server. I've attached the logs I collected.

The case6-quant*.out has the output of the server console which prints the stack trace.

I used the following commit for quant
* bf903dd1 (HEAD -> master, origin/master, origin/HEAD) Fixes for RIOT

Let me know if I can help with reproducing the issue. I used a modified lsquic echo client.

Thanks,

Kash

[quant.zip](https://github.com/NTAP/quant/files/5136950/quant.zip)

**Comment by larseggert** [comment]
Thanks for the report! I think I fixed (and similar cases) this a week or two ago. Could you test the current version?

**Comment by larseggert** [comment]
Specifically, I think 1f30850826e5f41af3a2649e7f63f6a29a8b9b62 fixed this.

**Comment by hashkash** [comment]
I tested the latest commit and it still crashes

...
153.261   log_pkt pkt.c:119 RX from=10.0.2.2:49723 len=91 0x41=Short kyph=0 spin=0 dcid=0:74450c6d nr=3
          dec_new_cid_frame frame.c:1085 NEW_CONNECTION_ID seq=1 rpt=0 len=8 dcid=1:0100000000000000 srt=181df58a9c3a4ace450b5108ef7de096
          dec_new_cid_frame frame.c:1085 NEW_CONNECTION_ID seq=2 rpt=0 len=8 dcid=2:0100000000000000 srt=181df58a9c3a4ace450b5108ef7de096
153.261   conns_by_srt_ins conn.c:743 ABORT: assertion failed:
        ret >= 1
inserted returned 0 errno 0 =

**Comment by larseggert** [comment]
Thanks for checking! I will look into this next week.

**Comment by larseggert** [comment]
Could you recheck the latest version? Also, if your tool available?

**Comment by hashkash** [comment]
Just checked it and it doesn't crash. Thanks for fixing it.

It's still very hacky code so it's not yet public.

**Comment by larseggert** [comment]
Great! Let me know when your code is available and/or when you find new issues!
